### ISSUE TITLE
Examine new Java 8 default methods and possibly reimplement for various EventList types

### ISSUE THREAD

**Issue by hbrands** [glazedlists/glazedlists#644]
new Java 8 default methods are

**java.lang.Iterable:**
default void forEach(Consumer<? super T> action)
default Spliterator<E> spliterator()

**java.util.Collection:**
default boolean removeIf(Predicate<? super E> filter)
default Spliterator<E> spliterator()
default Stream<E> stream()
default Stream<E> parallelStream()

**java.util.List:**
default void replaceAll(UnaryOperator<E> operator)
default void sort(Comparator<? super E> c)
default Spliterator<E> spliterator()

**java.util.ArrayList:**
public Spliterator<E> spliterator()

Examine and decide if we need to reimplement some default methods in various EventList implementations.
For example, ThreadSafeList needs to override these methods to fullfill its contract, that is obtaining a ReadWriteLock for all operations.
There might be other cases as well.

**Comment by robeden** [comment]
forEach is a huge performance win given GL locking. I've overridden it in our extension to FunctionList with huge performance wins.

**Comment by fab1an** [comment]
I have a problem here: Java 8 still isn't supported completely by android. Some parts are (default methods), but some (java.util.function, java.util.stream) are not.

https://developer.android.com/studio/write/java8-support.html

I don't mind this in my code, since i'm writing kotlin anyway which brings all of these things to java6, but I still would like to use glazedlists on android in the future.

Doesn't matter for now, I will check for issues when a new glazedlists release comes up.

**Comment by hbrands** [comment]
@fab1an On the one hand I can understand that Java 8 seems to be fully supported only on Android Nougat onwards. On the other hand, Java 8 was released back in March 2014. We're now in 2018 and I think it's time for Glazed Lists to move to Java 8 as baseline and use it's features. BTW, we moved quite slowly to new java versions, so we don't want to wait longer.
@robeden WDYT?

**Comment by fab1an** [comment]
I agree. And if something comes up we‘ll find a solution.

**Comment by robeden** [comment]
Well, this is always an issue with every project I work with. The slowpoke used to always be WebSphere. Now it's Android. The inverse of fab1an's problem is that (for example) I'm on a pure Java platform and not having better support of Java 8 features (Java 9's looking pretty good too! 😉) is rough.

My personal opinion is this: if libraries try to hang back with the common denominator, they get left behind. People who need older versions don't need to update, but those who need newer features have no option if we hang back.

Now, it would obviously be nice to support Android if we have users there (and obviously we do since @fab1an is one). So, my recommendation is we move to current APIs for the master and future branches and keep a 1.7 support branch (1.11.x) while it makes sense. We can back port a much as there's interest in having.

**Comment by fab1an** [comment]
Sounds good!

**Comment by robeden** [comment]
I believe AbstractEventList and BasicEventList are complete. I'll not start digging through some of the other main list implementations to see if they should do anything special.

**Comment by robeden** [comment]
Note to self (and possibly others): with that latest batch of changes, a number of performance improvements we had at work are now available with FunctionListMap and BasicEventList. A number of usages of ListIterator have been removed (which is always good because the GL ListIterator is *extremely* heavyweight).

**Comment by hbrands** [comment]
Hi @robeden,
most of the changes look good to me :+1: 
here are some comments/discussions for minor things:

1. overrides in TransformedList
Now that #clear, #removeAll and #retainAll are implemented in terms of #removeIf in AbstractEventList,
I think we only need to override #removeIf in TransformedList and can remove the overrides for #clear, #removeAll and #retainAll there.

2. AbstractEventList#replaceAll(UnaryOperator)
Your implementation uses beginEvent/commitEvent which doesn't match the current implementation pattern for the other methods. I suggest to omit beginEvent/commitEvent there and overwrite it in Transformed List - analog to the other method implementations.

3. FunctionListMap optimization
The Map put operation now behaves differently in an edge case when putting null values.
Here is a test case that fails now:
```
    @Test
    public void testPutNull() {
        final EventList<String> source = new BasicEventList<String>();
        source.add("Jesse");
        source.add(null);
        source.add("Katie");
        final Map<String, String> eventMap = GlazedLists.syncEventListToMap(source, new FirstLetterOrNullFunction());
        assertEquals(3, eventMap.size());
        assertEquals("Jesse", eventMap.get("J"));
        assertEquals("Katie", eventMap.get("K"));
        assertEquals(null, eventMap.get("UNKNOWN"));
        assertEquals(null, eventMap.put("UNKNOWN", null));
        assertEquals(3, eventMap.size());
        assertEquals("Jesse", eventMap.get("J"));
        assertEquals("Katie", eventMap.get("K"));
        assertEquals(null, eventMap.get("UNKNOWN"));
    }

    private static final class FirstLetterOrNullFunction implements FunctionList.Function<String, String> {
        @Override
        public String evaluate(String sourceValue) {
            return sourceValue == null ? "UNKNOWN" : String.valueOf(sourceValue.charAt(0));
        }
    }
```
That is, because the put method doesn't use containsKey anymore but "only" looks at the contained value. I think we should revert to the old behaviour or document the change in behaviour.

**Comment by robeden** [comment]
1. Well, actually that probably reveals a slight issue. The `clear()` in `TransformedList` wraps in a nest-able event (see my reply to #2) where the clear implementation in `AbstractEventList` doesn't. The implementation in `AbstractEventList` probably should. Otherwise, yes, the override in `TransformedList` is unnecessary (though not harmful). I have a unit test for this somewhere (will update once found).

2. The `replaceAll` is in a nest-able event block to cause one event to be fired for the operation. As far as I'm aware, there are no similar methods in `AbstractEventList` itself, though the `TransformedList.clear()` method is a similar approach and –as discussed previously– it does use the same block. The event needs to be nested because the default implementation calls to `set` which would be inside an event block.

3. I'll look at this in a bit.

4. I'll look at this, but I don't know that we need to do anything at the moment. The only place I would care a lot for now is if it's using `ListIterator` (haven't looked). GL's `ListIterator` implementation is ridiculously heavy-weight so I avoid it at all costs.

5. Oh, sorry. I try really hard to match style but I must have missed a few. You're welcome to change them, but I'm also happy to clean them up. (Feel free to point me to where I did it so I don't miss them.)

Rob's todo list:
- [ ] Consider event block in `AbstractEventList.clear`
- [ ] Find event block unit test and update comment
- [ ] Convert sneaky snake_case variables to camelCase (even though snake_case is clearly better 😉)
- [ ] Consider FunctionList behavior change
- [ ] Consider `List.sort`

**Comment by hbrands** [comment]
I mentioned the first two points based on my understanding and assumption that AbstractEventList provides only the "business logic" of the list methods and TransformedList adds the event batching (beginEvent/commitEvent) on top of it. So users would have a choice how to write their own EventLists (usually by extending TransformedList).

Now, with the recent changes you moved the task of list event handling (beginEvent/commitEvent) one level up to AbstractEventList, which is not incorrect but also not in line with the former implementation convention of AbstractEventList/TransformedList.

But I'm fine with that change as long as it's consistent. We should probably document this change in the release notes and/or migration guide later.

See my other comments in your PR #662

**Comment by robeden** [comment]
Ok, I think I see what you're getting at. I guess I haven't seen it that way, though we could take that approach. The documentation doesn't particularly read that way to me:

> A convenience class that implements common functionality for all `EventList`s.
>
> If you are creating a custom `EventList`, consider extending the more feature-rich `TransformedList`.

I agree that it says `TransformedList` is "more feature rich", but I've never read that as omitting things like nested events. Now, I admit I haven't done any performance testing on nested events versus, but a cursory look seems like there shouldn't be any real significant performance penalty of nested over singe-level events. To me they see like something all list should be doing, so guess I'm not seeing it as "extra"... unless you know of some reason that what I said isn't right. It's very possible.

Practically, there are three things that extend `AbstractEventList`: `BasicEventList`, `DebugList` and `TransformedList`. If we don't implemented that stuff in `AbstractEventList`, we'd need to at least do the same thing in `BasicList and `TransformedList` (don't know about `DebugList`... haven't thought about it yet).

**Comment by robeden** [comment]
I should add: motivation generally comes from the viewpoint that handling an event is much more expensive than handling sub-pieces of an event. So, batching is a big thing for me, generally. I can easily see orders of magnitude performance issues when events aren't batched. ... which is generally why I get all whiney when batching breaks. 😉

**Comment by hbrands** [comment]
I also understand your viewpoint which is perfectly fine.
Now we have correct list event handling on the level of AbstractEventList. I think only Jesse can tell why it was previously applied only on TransformedList.
But let's move on, feel free to commit the outstanding changes.
I'll make a note in the migration guide for those users who extended AbstractEventList directly.

**Comment by hbrands** [comment]
@robeden Do you have pending changes you want to push for version 1.12? Else I would want to close this issue. I'd suggest to prepare a release for 1.12 in the next days with what we have right now.

**Comment by hbrands** [comment]
Hi Rob (@robeden),
I hope you are doing fine.
Should we close this issue?

**Comment by robeden** [comment]
Hi @hbrands. I’m sorry I missed your ping earlier this year. Things are well here. I hope you’re having a good holiday season!

I don’t have anything to add here. I think it’s in decent shape as-is.
